backend:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'web/**'
          - '!web/**/*.md'

devops:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'Dockerfile*'
          - 'docker-compose*.yml'
          - 'Makefile'
          - '.air.toml'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

database:
  - changed-files:
      - any-glob-to-any-file:
          - '**/migrations/**'
