codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "cmd/**/*"
  - "**/*_test.go"
  - "docs/**/*"

flags:
  internal:
    paths:
      - internal/
    carryforward: true
