codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "cmd/**/*"
  - "**/*_test.go"
  - "docs/**/*"
  - "internal/cli/**/*"  # CLI has integration tests, unit coverage less critical

flags:
  internal:
    paths:
      - internal/
    carryforward: true
