ALTER TABLE tasks ADD COLUMN IF NOT EXISTS liveness_probe JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS readiness_probe JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS restart_policy VARCHAR(50);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS health_status VARCHAR(50);
