-- +goose Up
-- +goose StatementBegin
ALTER TABLE nodes ALTER COLUMN last_heartbeat TYPE TIMESTAMPTZ;
ALTER TABLE tasks ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE tasks ALTER COLUMN started_at TYPE TIMESTAMPTZ;
ALTER TABLE tasks ALTER COLUMN finished_at TYPE TIMESTAMPTZ;
ALTER TABLE pods ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE pods ALTER COLUMN scheduled_at TYPE TIMESTAMPTZ;
ALTER TABLE pods ALTER COLUMN started_at TYPE TIMESTAMPTZ;
ALTER TABLE pods ALTER COLUMN finished_at TYPE TIMESTAMPTZ;
ALTER TABLE services ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE services ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE endpoints ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN last_login TYPE TIMESTAMPTZ;
ALTER TABLE api_keys ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE api_keys ALTER COLUMN expires_at TYPE TIMESTAMPTZ;
ALTER TABLE api_keys ALTER COLUMN last_used TYPE TIMESTAMPTZ;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE nodes ALTER COLUMN last_heartbeat TYPE TIMESTAMP;
ALTER TABLE tasks ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE tasks ALTER COLUMN started_at TYPE TIMESTAMP;
ALTER TABLE tasks ALTER COLUMN finished_at TYPE TIMESTAMP;
ALTER TABLE pods ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE pods ALTER COLUMN scheduled_at TYPE TIMESTAMP;
ALTER TABLE pods ALTER COLUMN started_at TYPE TIMESTAMP;
ALTER TABLE pods ALTER COLUMN finished_at TYPE TIMESTAMP;
ALTER TABLE services ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE services ALTER COLUMN updated_at TYPE TIMESTAMP;
ALTER TABLE endpoints ALTER COLUMN updated_at TYPE TIMESTAMP;
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE users ALTER COLUMN last_login TYPE TIMESTAMP;
ALTER TABLE api_keys ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE api_keys ALTER COLUMN expires_at TYPE TIMESTAMP;
ALTER TABLE api_keys ALTER COLUMN last_used TYPE TIMESTAMP;
-- +goose StatementEnd
